CREATE DATABASE BudgetManagement
GO

USE BudgetManagement
GO

CREATE TABLE Trade
(
Id INT IDENTITY(1, 1),
UserId INT NOT NULL,
TradeDate DATETIME NOT NULL,
Price INT NOT NULL,
OperationTypeId INT NOT NULL,
AccountId INT NOT NULL,
CategoryId INT NOT NULL,
Note NVARCHAR(1000) NULL,
CONSTRAINT PK_Trade PRIMARY KEY (Id)
)
GO

CREATE TABLE OperationType
(
Id INT IDENTITY(1, 1),
T_Description NVARCHAR(50) NOT NULL,
CONSTRAINT PK_TradeType PRIMARY KEY (Id)
)
GO

CREATE TABLE AccountType
(
Id INT IDENTITY(1, 1),
AT_Name NVARCHAR(50),
UserId INT NOT NULL,
AT_Order INT NOT NULL
CONSTRAINT PK_AccountType PRIMARY KEY (Id)
)
GO

CREATE TABLE Account
(
Id INT IDENTITY(1, 1),
A_Name NVARCHAR(50) NOT NULL,
AccountTypeId INT NOT NULL,
Balance INT NOT NULL,
A_Description NVARCHAR(1000) NULL,
CONSTRAINT PK_Account PRIMARY KEY (Id)
)
GO

CREATE TABLE AppUser
(
Id INT IDENTITY(1, 1),
Email NVARCHAR(256) NOT NULL,
NormalizedEmail NVARCHAR(256) NOT NULL,
PasswordHash NVARCHAR(MAX) NOT NULL,
CONSTRAINT PK_AppUser PRIMARY KEY (Id)
)
GO

CREATE TABLE Category
(
Id INT IDENTITY(1, 1),
C_Name NVARCHAR(50) NOT NULL,
OperationTypeId INT NOT NULL,
UserId INT NOT NULL,
CONSTRAINT PK_Category PRIMARY KEY (Id)
)
GO

ALTER TABLE Trade
ADD CONSTRAINT FK_Trade_OperationType
FOREIGN KEY (OperationTypeId) REFERENCES OperationType(Id)
GO

ALTER TABLE Trade
ADD CONSTRAINT FK_Trade_Account
FOREIGN KEY (AccountId) REFERENCES Account(Id)
GO

ALTER TABLE Trade
ADD CONSTRAINT FK_Trade_Category
FOREIGN KEY (CategoryId) REFERENCES Category(Id)
GO

ALTER TABLE Account
ADD CONSTRAINT FK_Account_AccountType
FOREIGN KEY (AccountTypeId) REFERENCES AccountType(Id)
GO

ALTER TABLE AccountType
ADD CONSTRAINT FK_AccountType_AppUser
FOREIGN KEY (UserId) REFERENCES AppUser(Id)
GO

ALTER TABLE Trade
ADD CONSTRAINT FK_Trade_AppUser
FOREIGN KEY (UserId) REFERENCES AppUser(Id)
GO

ALTER TABLE Category
ADD CONSTRAINT FK_Category_OperationType
FOREIGN KEY (OperationTypeId) REFERENCES OperationType(Id)
GO

ALTER TABLE Category
ADD CONSTRAINT FK_Category_AppUser
FOREIGN KEY (UserId) REFERENCES AppUser(Id)
GO